.\" .TH = title header, .SH = section header, .B = bold
.\" .PP = paragraph, .TP = indent 2 lines after
.\"
.\" .SH EXAMPLES
.\" To write some text to the standard output, use the
.\" .BR printf (1)
.\" command:
.\" .PP
.\" .nf
.\" .RS
.\" printf "this is a %s format %s\n" \\
.\" usual string
.\" .RE
.\" .fi
.\" .PP
.\" Nifty, huh?
.\"
.TH ONEBOOK 1 "August, 2021"
.SH NAME
onebook \- a universal bookmark manager
.SH SYNOPSIS
.B onebook
[options] <subcommands> <args>
.SH DESCRIPTION
.B onebook
is a simple bookmark manager, designed to aggregate all your bookmarks into a single location.

It uses the filesystem as a means to store the information so as to let the data be worked with easily, in any language.
.SH OPTIONS
.TP
\-h, \-\-help
Display the help message
.SH COMMANDS
.TP
init
Initialize the program. Create a configuration file and Onebook's storage directory, if none exist.
.TP
import <browser\-name>
Import bookmarks from a browser and store them in Onebook's storage. Case\-insensitive.
