# A default configuration file for onebook in yaml (with documentation)

---
export:
  default_browsers:
    - chromium
    - chrome
    - safari
    - firefox
    - qutebrowser
import:
  default_browser:
    - chromium
    - chrome
    - safari
    - firefox
    - qutebrowser
sync:
  default_browsers:
    - chromium
    - chrome
    - safari
    - firefox
    - qutebrowser
...
