* SafariBookmarkManager
  :PROPERTIES:
  :CUSTOM_ID: safaribookmarkmanager
  :END:

#+BEGIN_SRC swift
extension BookmarkManager {
    struct SafariBookmarkManager {...}
}
#+END_SRC

A struct with properties and methods pertaining to Safari bookmarks.

** Properties
  :PROPERTIES:
  :CUSTOM_ID: properties
  :END:
** Methods
  :PROPERTIES:
  :CUSTOM_ID: methods
  :END:
*** getBookmarks
  :PROPERTIES:
  :CUSTOM_ID: getbookmarks
  :END:

#+BEGIN_SRC swift
public func getBookmarks(from bookmarksFilePath: URL) -> Data? {...}
#+END_SRC

A method to retrieve Safari bookmarks from the file specified at the
URL given as a parameter. Returns =Data?=.

*** parseBookmarks
  :PROPERTIES:
  :CUSTOM_ID: parsebookmarks
  :END:

#+BEGIN_SRC swift
public func parseBookmarks(_ bookmarksDump: Data?) -> SafariBookmarks? {...}
#+END_SRC

A method to parse the bookmark data provided to it as a parameter. Returns
=SafariBookmarks??=.

*** storeBookmarks
  :PROPERTIES:
  :CUSTOM_ID: storebookmarks
  :END:

#+BEGIN_SRC swift
public func storeBookmarks(_ bookmarksData: SafariBookmarks, storeAt storageDirectory: String) {...}
#+END_SRC

A method to store the bookmarks (of type =SafariBookmarks=) provided to it as
a parameter, at the directory provided as a parameter, which is given as a
string. Null return.
